### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by McSinyx**

### CODE REVIEW

**Comment by pdhlong** [comment]
But but I still can't run it :(

**Comment by McSinyx** [comment]
Which error do you get?  Presumably you have all the dependencies (trio, httpx, html5lib) installed.

**Comment by pdhlong** [comment]
Yup at least the UnicodeEncodeError one.

**Comment by McSinyx** [comment]
Ugh Windows :disappointed:  It's 2020 and Unicode still don't have 1st class support.

**Comment by pdhlong** [comment]
Yeah I'm using win7 so I can't even install Python39. Guess that's my fault then, I'll test this evening.

**Comment by McSinyx** [comment]
It should run on any Python ≥ 3.6, my guess was that I need to specify the encoding since Windows doesn't default to UTF-8 like every other OSes

**Review by pdhlong — APPROVED** [review]
Solved.

**Pull request merged**
