### PR TITLE
Scrape from VnExpress

### PR DESCRIPTION
**Pull request by McSinyx**
Let's use trio for async networking, httpx for, ehm, HTTP stuff and html5lib for HTML5 parsing.

For Dân Trí and Tuổi Trẻ it should be done similarly.

### CODE REVIEW

**Review by thanhnguyen0908 — COMMENTED** [review]
Aight I think that would be cool

**Comment by McSinyx** [comment]
Thanks, may I have your approval then?

**Review by quangLH195 — APPROVED** [review]
thanks for your work, but should we add dantri.com and tuoitre.net later ? and should we writting source and caption of image into JSON file ? If you need anything please tell me and I will complete them as soon as possible

**Comment by McSinyx** [comment]
> should we add dantri.com and tuoitre.net

Yes.  If you feel like it, please work on one of these and let another do the other since we're required to distribute the work among the team.

> should we writting source and caption of image into JSON file

No, since we only need the image and caption, which now presents.

**Pull request merged**
